/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ClearAdmin: typeof import('./components/TxDialog/wasm/ClearAdmin.vue')['default']
    ConnectWallet: typeof import('./components/ConnectWallet/ConnectWallet.vue')['default']
    ConnectWalletMenu: typeof import('./components/ConnectWallet/ConnectWalletMenu.vue')['default']
    Delegate: typeof import('./components/TxDialog/messages/Delegate.vue')['default']
    Deposit: typeof import('./components/TxDialog/messages/Deposit.vue')['default']
    ExecuteContract: typeof import('./components/TxDialog/wasm/ExecuteContract.vue')['default']
    InstantiateContract: typeof import('./components/TxDialog/wasm/InstantiateContract.vue')['default']
    MigrateContract: typeof import('./components/TxDialog/wasm/MigrateContract.vue')['default']
    MigrateContract2: typeof import('./components/TxDialog/wasm/MigrateContract2.vue')['default']
    Redelegate: typeof import('./components/TxDialog/messages/Redelegate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Send: typeof import('./components/TxDialog/messages/Send.vue')['default']
    StoreCode: typeof import('./components/TxDialog/wasm/StoreCode.vue')['default']
    Transfer: typeof import('./components/TxDialog/messages/Transfer.vue')['default']
    TxDialog: typeof import('./components/TxDialog/TxDialog.vue')['default']
    TxPrepareDialog: typeof import('./components/TxDialog/TxPrepareDialog.vue')['default']
    TxProgressDialog: typeof import('./components/TxDialog/TxProgressDialog.vue')['default']
    Unbond: typeof import('./components/TxDialog/messages/Unbond.vue')['default']
    UpdateAdmin: typeof import('./components/TxDialog/wasm/UpdateAdmin.vue')['default']
    Vote: typeof import('./components/TxDialog/messages/Vote.vue')['default']
    WalletInfoMenu: typeof import('./components/ConnectWallet/WalletInfoMenu.vue')['default']
    Withdraw: typeof import('./components/TxDialog/messages/Withdraw.vue')['default']
    WithdrawCommission: typeof import('./components/TxDialog/messages/WithdrawCommission.vue')['default']
  }
}
